services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
      - "5555:5555"

  
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend

